version: '3'
services:
  mongodb:
    image: leonlei1983/mongodb:3.4
    environment:
      MONGODB_USER: root
      MONGODB_PASS: 1qaz2wsx
      MONGODB_DATABASE: darko_test
      CACHE_SIZE_GB: 2
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/mongodb:/data/dbsql/data
